//
//  ListStudentsModels.swift
//  Bloom Into You
//
//  Created by Hafizh Mo on 22/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListStudents {
  
  enum LoadStudents {
    struct Request {}
    
    struct Response {
      var student: [Student]
    }
    
    struct ViewModel {
      var students: [Student]
    }
  }
  
}
